[project]
name = "my-new-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
    "pytest-html>=3.2.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
